name: Deploy Nuxt3 Static 

on: 
  push: 
    branches: 
      - develop

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2 

      - name: Set up Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: '22' 

      - name: Install dependencies 
        run: npm install 

      - name: Generate static site 
        run: |
          npm run generate:prod || true
          pkill -f 'nuxt' || true
 
      - name: Upload artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: nuxt-dist 
          path: .output/public 

  deploy: 
    needs: build 
    runs-on: ubuntu-latest 

    steps: 
      - name: Download artifact 
        uses: actions/download-artifact@v4 
        with: 
          name: nuxt-dist 
          path: nuxt-dist 

      - name: Deploy to server 
        uses: appleboy/scp-action@master 
        with: 
          host: ${{ secrets.SSH_HOST }} 
          username: ${{ secrets.SSH_USERNAME }} 
          key: ${{ secrets.SSH_KEY }} 
          source: "nuxt-dist/*" 
          target: "/var/www/pereztour.tshdevelop.com/dist" 
          strip_components: 1 