name: Publish Website to HML

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy to HML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release

      - name: Build project
        run: |
          npm install
          npm run generate

      - name: Clean Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            rm -rf /home/git/projects/hml.tsh.pereztour/*

      - name: Deploy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: ".output/public/*"
          target: "/home/git/projects/hml.tsh.pereztour"