name: Publish Website to HML

on:
  push:
    branches:
      - release

jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release

      - name: Build project
        run: |
          npm install
          npm run generate

      - name: List generated files
        run: ls -l dist

      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: /home/git/projects/hml.tsh.pereztour
          remote-port: 22